### ISSUE TITLE
Ya no es valida la apiVersion extensions/v1beta1

### ISSUE THREAD

**Issue by sjuarezgx** [sebagomez/gx28k8sdemo#1]
Hola Seba, 
El .yaml del ejemplo ya no es valido, por lo que dice aca: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Te parece ok poner un disclaimer, o simplemente un link a este ejemplo, que seria el actualizado?
https://github.com/sebagomez/gx-k8s-gug

gracias!

**Comment by sebagomez** [comment]
Solucionado, gracias!
